[package]
name = "uww-math"
version = "1.0.0"
entrypoint = "uww-math.typ"
authors = ["Aspen Price <aspen@aspen-otr.com>"]
license = "Unlicense"
description = "Useful for University of Wisconsin-Whitewater courses"
